Repository CSC207-2022F-UofT/course-project-bill-gates, pull requests merged in 2022-12, with the labels that each got.

#65 [+] Extend the InsertEntryUseCase that can insert a new splitter entry.
  src/main/java/billgates/use_cases/insert_entry/InsertEntryRequestModel.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryUseCase.java
Labels: enhancement

#64 [*] Update AlterEntryUseCase
  src/main/java/billgates/use_cases/alter_entry/AlterEntryController.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryInputPort.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryRequestModel.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryUseCase.java
Labels: enhancement

#74 [+] Added javadoc for DeleteEntryUseCase
  src/main/java/billgates/use_cases/delete_entry/DeleteEntryController.java
  src/main/java/billgates/use_cases/delete_entry/DeleteEntryInputPort.java
  src/main/java/billgates/use_cases/delete_entry/DeleteEntryUseCase.java
Labels: documentation

#34 [+] Change color function [+] Change font function
  .gitignore
  src/main/java/billgates/view/gui/ActionButton.java
  src/main/java/billgates/view/gui/ActionLabel.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/ActionTextArea.java
  src/main/java/billgates/view/gui/BillPanel.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/CustomTitleBorder.java
  src/main/java/billgates/view/gui/FontSettings.java
  src/main/java/billgates/view/gui/MainFrame.java
  src/main/java/billgates/view/gui/SettingDialog.java
  src/main/java/billgates/view/gui/TopMenuBar.java
Labels: enhancement

#77 [+] Add Javadoc for InsertEntryUseCase
  src/main/java/billgates/use_cases/delete_entry/DeleteEntryUseCase.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryController.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryInputPort.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryRequestModel.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryUseCase.java
Labels: documentation

#71 [+] Implement a new dialog for adding an entry
  src/main/java/billgates/Main.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/MainFrame.java
Labels: enhancement

#73 [*] Made bill update run asynchronously and added supports for bill splitter.
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/use_cases/bill_update/BillUpdateUseCase.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/BillPanel.java
Labels: enhancement

#76 [*] Revamped `MySQLDatabaseGateway` and other major modifications to use cases
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/database/QueryBillData.java
  src/main/java/billgates/database/QueryEntry.java
  src/main/java/billgates/database/QueryEntryData.java
  src/main/java/billgates/database/QuerySplitBillData.java
  src/main/java/billgates/database/QuerySplitEntryData.java
  src/main/java/billgates/entities/EntryBuilder.java
  src/main/java/billgates/entities/InvalidEntryException.java
  src/main/java/billgates/entities/QueryUserData.java
  src/main/java/billgates/entities/User.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryRequestModel.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryUseCase.java
  src/main/java/billgates/use_cases/bill_update/BillUpdateUseCase.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryUseCase.java
  src/main/java/billgates/use_cases/user_join/UserJoinUseCase.java
  src/test/java/database/MySQLDatabaseGatewayTests.java
Labels: enhancement

#85 [*] Changed the back button icon.
  src/main/resources/back.png
Labels: enhancement

#82 [*] Connected the alter entry use case to the GUI and added support for splitter bill.
  src/main/java/billgates/Main.java
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/entities/AbstractEntry.java
  src/main/java/billgates/entities/Entry.java
  src/main/java/billgates/entities/EntryBuilder.java
  src/main/java/billgates/entities/QueryUserData.java
  src/main/java/billgates/entities/SplitterEntry.java
  src/main/java/billgates/entities/User.java
  src/main/java/billgates/interface_adapters/BillPanelUpdatable.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/main/java/billgates/interface_adapters/UserJoinUpdatable.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryController.java
  src/main/java/billgates/use_cases/alter_entry/AlterEntryUseCase.java
  src/main/java/billgates/use_cases/bill_update/BillUpdateOutputPort.java
  src/main/java/billgates/use_cases/bill_update/BillUpdatePresenter.java
  src/main/java/billgates/use_cases/bill_update/BillUpdateViewModel.java
  src/main/java/billgates/use_cases/delete_entry/DeleteEntryInputPort.java
  src/main/java/billgates/use_cases/delete_entry/DeleteEntryUseCase.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryInputPort.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryRequestModel.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryUseCase.java
  src/main/java/billgates/use_cases/user_join/UserJoinInputPort.java
  src/main/java/billgates/use_cases/user_join/UserJoinRequestModel.java
  src/main/java/billgates/use_cases/user_join/UserJoinUseCase.java
  src/main/java/billgates/view/gui/ActionButton.java
  src/main/java/billgates/view/gui/ActionLabel.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/BillPanel.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/ConstraintTableCellEditor.java
  src/main/java/billgates/view/gui/CustomTitleBorder.java
  src/main/java/billgates/view/gui/MainFrame.java
  src/main/java/billgates/view/gui/SettingDialog.java
  src/main/java/billgates/view/gui/TopMenuBar.java
  src/test/java/database/MySQLDatabaseGatewayTests.java
Labels: enhancement

#83 [+] Use `LGoodDatePicker.DatetimePicker` to edit the date
  build.gradle
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/AddEntryDialog.java
Labels: enhancement

#90 [*] Improved the add entry dialog and added support for splitter entry.
  src/main/java/billgates/Main.java
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/main/java/billgates/use_cases/bill_update/BillUpdatePresenter.java
  src/main/java/billgates/use_cases/insert_entry/InsertEntryRequestModel.java
  src/main/java/billgates/view/BillGatesUtilities.java
  src/main/java/billgates/view/gui/ActionComboBox.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/ActionTextField.java
  src/main/java/billgates/view/gui/AddEntryDialog.java
  src/main/java/billgates/view/gui/BillTable.java
  src/test/java/database/MySQLDatabaseGatewayTests.java
Labels: enhancement

#88 [+] Fix convention issues for MenuBar
  src/main/java/billgates/view/gui/TopMenuBar.java
Labels: documentation, enhancement

#89 [+] Used the date time picker as the editor of the date column of the table.
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/DateTableCellEditor.java
  src/main/java/billgates/view/gui/MainFrame.java
Labels: enhancement

#97 [*] change some shortcut keys to avoid conflict
  src/main/java/billgates/view/gui/TopMenuBar.java
Labels: enhancement

#96 [+] Added tests for `BillUpdateUseCase`.
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/entities/User.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/main/java/billgates/use_cases/bill_update/BillUpdateUseCase.java
  src/main/java/billgates/use_cases/bill_update/BillUpdateViewModel.java
  src/main/java/billgates/view/BillGatesUtilities.java
  src/main/java/billgates/view/gui/AddEntryDialog.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/ConstraintTableCellEditor.java
  src/test/java/billgates/TestUtilities.java
  src/test/java/billgates/database/MySQLDatabaseGatewayTests.java
  src/test/java/billgates/use_cases/BillUpdateUseCaseTest.java
Labels: enhancement

#100 [*] Fixed back button bug and behavior of altering date and currency column.
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/BillDefaultTableCellEditor.java
  src/main/java/billgates/view/gui/BillPanel.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/DateTableCellEditor.java
  src/main/java/billgates/view/gui/MainFrame.java
Labels: bug

#103 [+] Added an auto-release GitHub Actions Script
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/billgates/database/MySQLDatabaseGateway.java
Labels: documentation, enhancement

#102 [*] Fixed the bug when reorder the columns of the table & Adjust…
  src/main/java/billgates/view/gui/ActionTextArea.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/MainFrame.java
Labels: bug, enhancement

#110 [*] Changed the font of the table & setting dialog
  src/main/java/billgates/view/gui/FontSettings.java
  src/main/java/billgates/view/gui/SettingDialog.java
  src/main/java/billgates/view/gui/TopMenuBar.java
Labels: enhancement

#112 [+]Fixed problems and the csv file imported can be revealed in the screen!
  src/main/java/billgates/view/gui/MainFrame.java
  src/main/java/billgates/view/gui/TopMenuBar.java
Labels: enhancement

#114 [+] Added implementation of UserJoinUseCaseTest.
  src/main/java/billgates/use_cases/user_join/UserJoinViewModel.java
  src/test/java/billgates/use_cases/UserJoinUseCaseTests.java
Labels: enhancement

#111 [+] add DeleteEntryUseCaseTest
  src/test/java/billgates/use_cases/DeleteEntryUseCaseTest.java
  src/test/java/billgates/use_cases/InsertEntryUseCaseTests.java
Labels: enhancement

#95 [+] Updated README.md
  README.md
  resources/flow_of_control.png
Labels: documentation

#115 [*] Changed the font of the table to Microsoft YaHei UI
  src/main/java/billgates/view/gui/FontSettings.java
  src/main/java/billgates/view/gui/TopMenuBar.java
Labels: bug

#116 [*] Removed warning of duplicated lines in IntelliJ
  src/main/java/billgates/database/MySQLDatabaseGateway.java
Labels: enhancement
