Repository CSC207-2022F-UofT/course-project-bill-gates, pull requests merged in 2022-11, with the labels that each got.

#26 [*] Modified database gateway code to align with Improvement 1
  src/main/java/billgates/database/DatabaseGateway.java
  src/main/java/billgates/database/MySQLDatabaseGateway.java
Labels: enhancement

#29 [+] Added an initial implementation of BillUpdateUseCase.
  src/main/java/billgates/Main.java
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/database/QueryEntryData.java
  src/main/java/billgates/entities/AbstractEntry.java
  src/main/java/billgates/entities/Entry.java
  src/main/java/billgates/entities/EntryBuilder.java
  src/main/java/billgates/entities/InvalidEntryException.java
  src/main/java/billgates/entities/User.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/main/java/billgates/interface_adapters/Updatable.java
  src/main/java/billgates/usecases/bill_update/BillUpdateController.java
  src/main/java/billgates/usecases/bill_update/BillUpdateInputPort.java
  src/main/java/billgates/usecases/bill_update/BillUpdateOutputPort.java
  src/main/java/billgates/usecases/bill_update/BillUpdatePresenter.java
  src/main/java/billgates/usecases/bill_update/BillUpdateResponseModel.java
  src/main/java/billgates/usecases/bill_update/BillUpdateUseCase.java
  src/main/java/billgates/usecases/bill_update/BillUpdateViewModel.java
  src/main/java/billgates/view/BillTableModel.java
  src/main/java/billgates/view/gui/BillDemo.java
  src/main/resources/config.properties
Labels: enhancement

#20 [+] Basic view of our GUI (Still in progress)
  src/main/java/billgates/view/gui/ActionButton.java
  src/main/java/billgates/view/gui/ActionLabel.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/ActionTextArea.java
  src/main/java/billgates/view/gui/BillPanel.java
  src/main/java/billgates/view/gui/BillTable.java
  src/main/java/billgates/view/gui/CustomTitleBorder.java
  src/main/java/billgates/view/gui/FontSettings.java
  src/main/java/billgates/view/gui/GeneralMenu.java
  src/main/java/billgates/view/gui/MainFrame.java
  src/main/java/billgates/view/gui/SwingUtil.java
  src/main/java/billgates/view/gui/TopMenuBar.java
  src/main/resources/back.png
Labels: enhancement, help wanted

#39 [+] Add deleteEntry Usecase
  src/main/java/billgates/usecases/delete_entry/DeleteEntryController.java
  src/main/java/billgates/usecases/delete_entry/DeleteEntryInputPort.java
  src/main/java/billgates/usecases/delete_entry/DeleteEntryUseCase.java
Labels: enhancement

#43 [+] Implemented InsertEntryUseCase
  src/main/java/billgates/usecases/insert_entry/InsertEntryController.java
  src/main/java/billgates/usecases/insert_entry/InsertEntryInputPort.java
  src/main/java/billgates/usecases/insert_entry/InsertEntryRequestModel.java
  src/main/java/billgates/usecases/insert_entry/InsertEntryUseCase.java
Labels: enhancement

#41 [+] Implemented AlterEntryUseCase_light version
  src/main/java/usecase/alter_entry/AlterEntryController.java
  src/main/java/usecase/alter_entry/AlterEntryInputPort.java
  src/main/java/usecase/alter_entry/AlterEntryRequestModel.java
  src/main/java/usecase/alter_entry/AlterEntryUseCase.java
Labels: enhancement

#31 [+] Added Unit tests for MySQLDatabaseGateway & Extra modifications within the class
  build.gradle
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/database/QueryEntryData.java
  src/main/java/billgates/database/QueryUserData.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/test/java/database/MySQLDatabaseGatewayTests.java
Labels: bug, enhancement

#47 [+] Modified MySQLDatabaseGateway to allow splitBill feature
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/test/java/database/MySQLDatabaseGatewayTests.java
Labels: enhancement

#50 [+] Included Javadocs, fixed Main.java for Mac, modified logic for getBillData, update README.md
  README.md
  src/main/java/billgates/Main.java
  src/main/java/billgates/database/MySQLDatabaseGateway.java
  src/main/java/billgates/interface_adapters/DatabaseGateway.java
  src/test/java/database/MySQLDatabaseGatewayTests.java
Labels: documentation, enhancement

#49 [+] Modify UserJoinUseCase and connect it with our GUI
  src/main/java/billgates/Main.java
  src/main/java/billgates/entities/User.java
  src/main/java/billgates/use_cases/user_join/UserJoinUseCase.java
  src/main/java/billgates/view/gui/ActionPanel.java
  src/main/java/billgates/view/gui/BillDemo.java
  src/main/java/billgates/view/gui/MainFrame.java
  src/main/java/billgates/view/gui/RegexDocument.java
Labels: enhancement

#63 [+] Added javadoc for userjoin use case.
  src/main/java/billgates/interface_adapters/UserJoinUpdatable.java
  src/main/java/billgates/use_cases/user_join/UserJoinController.java
  src/main/java/billgates/use_cases/user_join/UserJoinInputPort.java
  src/main/java/billgates/use_cases/user_join/UserJoinOutputPort.java
  src/main/java/billgates/use_cases/user_join/UserJoinPresenter.java
  src/main/java/billgates/use_cases/user_join/UserJoinRequestModel.java
  src/main/java/billgates/use_cases/user_join/UserJoinResponseModel.java
  src/main/java/billgates/use_cases/user_join/UserJoinUseCase.java
  src/main/java/billgates/use_cases/user_join/UserJoinViewModel.java
Labels: documentation
